---
- hosts: leafs
  gather_facts: no
  connection: local

  roles:
    - arista.eos-system
    - arista.eos-bridging
    - arista.eos-interfaces
    - arista.eos-ipv4
    - arista.eos-route-control
    - arista.eos-bgp
    - arista.eos-mlag
    - arista.eos-virtual-router
