---
- name: GATHER INFORMATION FROM SWITCHES
  hosts: arista
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER SWITCH FACTS
      eos_facts:

    - name: DISPLAY VERSION
      debug:
        msg: "The EOS version is: {{ ansible_net_version }}"

    - name: DISPLAY HOSTNAME
      debug:
        msg: "The hostname is: {{ ansible_net_hostname }}"

    - name: COLLECT OUTPUT OF SHOW COMMANDS
      eos_command:
        commands:
          - show run | i hostname
          - show ip interface brief
      tags: show
      register: show_output

    - name: DISPLAY THE COMMAND OUTPUT
      debug:
        var: show_output
      tags: show

    - name: DISPLAY THE HOSTNAME AGAIN
      debug:
        msg: "The hostname is {{ show_output.stdout[0] }}"
      tags: show
