---
- name: DEMONSTRATE CUSTOM FILTERS
  hosts: arista
  connection: network_cli
  gather_facts: no

  tasks:
    - name: RUN CUSTOM MODULE
      my_custom_module:
        option_one: '1'
        option_two: 'notnone'
        option_three: 'othervalue'
      register: result

    - name: DISPLAY CUSTOM MODULE RESULTS
      debug:
        msg: "{{ result }}"
