---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: arista
  connection: network_cli
  gather_facts: no

  tasks:
    - name: BACKUP THE CONFIG
      eos_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./backup/{{inventory_hostname}}.config"

    - name: REMOVE LOGGING LINE
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        line: "logging host 192.168.0.200"
        state: absent

    - name: REMOVE SNMP LINES - REGEXP
      lineinfile:
        path: "./backup/{{inventory_hostname}}.config"
        regexp: 'snmp-server community ansible-.*'
        state: absent
