---
- name: GENERATE MODEL/VERSION REPORT FROM SWITCHES
  hosts: arista
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER SWITCH FACTS
      eos_facts:

    - name: ENSURE REPORTS FOLDER
      run_once: true
      file:
        name: reports
        state: directory

    - name: RENDER FACTS AS A REPORT
      template:
        src: switch_info_report.j2
        dest: reports/{{ inventory_hostname }}.md

    - name: CONSOLIDATE THE EOS DATA
      assemble:
        src: reports/
        dest: switches_info_report.md
      delegate_to: localhost
      run_once: yes
