---
- name: GATHER INFORMATION FROM SWITCHES
  hosts: arista
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER SWITCH FACTS
      eos_facts:

    - name: DISPLAY VERSION
      debug:
        msg: "The EOS version is: {{ ansible_net_version }}"

    - name: DISPLAY HOSTNAME
      debug:
        msg: "The hostname is:{{ ansible_net_hostname }}"
