---
- name: UPDATE THE SNMP RO/RW STRINGS
  hosts: arista
  gather_facts: no
  connection: network_cli

  tasks:

    - name: ENSURE THAT THE DESIRED SNMP STRINGS ARE PRESENT
      eos_config:
        commands:
          - snmp-server community ansible-public ro
          - snmp-server community ansible-private rw
          - snmp-server community ansible-test ro


- name: GENERAL ENVIRONMENT CONFIGS FOR EOS SWITCHES
  hosts: arista
  gather_facts: no
  connection: network_cli

  tasks:

    - name: ENSURE THAT SWITHES ARE SECURE
      eos_config:
        src: general_switch.cfg
